server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    drive-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3333
  rabbitmq:
    host: 192.168.31.253
    port: 5672
    virtual-host: /design-admin
    username: design-admin
    password: design-admin
    listener:
      simple:
        prefetch: 1
    publisher-confirm-type: correlated #none关闭confirm, simple同步阻塞等待Mq回执消息, correlated 异步回调返回执消息
    #publisher-returns: true #开启publsiher 的return机制(返回回执)
    connection-timeout: 1s # 设置mq连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后等待的初始时间
        max-attempts: 3 # 最大重试次数
        multiplier: 1 #失败后下次等待时间的倍数

# mapper.xml文件现在必须和mapper接口文件放在相同目录下
mybatis:
  mapper-locations:
    classpath*: com\sunc\mapper\*.xml